# Stonecutters CS351 S03

# List all your client-specific .o files here!
OFILES=Curse.o Control.o Terrain.o Cview.o \
       CliConn.o CliHelloMsg.o CliMarkMsg.o CliChatMsg.o CliFailMsg.o \
       CliParamsMsg.o CliEmpireMsg.o CliCqMsg.o CliAlliesMsg.o \
       CliContactsMsg.o CliDoMsg.o CliTellMsg.o \
       main.o



CFLAGS += $(SOCKETINC) $(CURSESINC)
LFLAGS += $(SOCKETLIB) $(CURSESLIB)


 ALLDEP += $(COMMONLIBDEP)
