# Stonecutters CS351 S03
# $Id: Makefile,v 1.2 2003/04/18 23:35:44 rlpm Exp $

TOP=..
include $(TOP)/Makefile.vars$(MKSUFFIX)
include Makefile.vars$(MKSUFFIX)

all:	
	@echo "Made in Doc"

clean:
	rm -f *.o core *~ a.out

distclean: clean
