# Stonecutters CS351 S03

# List all your server-specific .o files here!
OFILES=Active.o Army.o Boat.o City.o Commander.o Cruiser.o Destroyer.o \
       Emperor.o Empire.o Land.o Mobile.o Static.o Water.o World.o Mountain.o \
       SvrChatMsg.o SvrHelloMsg.o SvrMarkMsg.o SvrFailMsg.o SvrParamsMsg.o \
       SvrCqMsg.o SvrAlliesMsg.o SvrContactsMsg.o SvrEmpireMsg.o SvrDoMsg.o \
       SvrTellMsg.o \
       main.o

CFLAGS += $(SOCKETINC)
LFLAGS += $(SOCKETLIB)

ALLDEP += $(COMMONLIBDEP)
