# Stonecutters CS351 S03

# List all your library .o files here!
OFILES=Connection.o Coord.o Countdown.o FrameParser.o Grid.o GridAble.o \
       Order.o Message.o Neighborhood.o Network.o Model.o ChatMsg.o \
       HelloMsg.o MarkMsg.o FailMsg.o ParamsMsg.o CqMsg.o AlliesMsg.o \
       ContactsMsg.o EmpireMsg.o DoMsg.o TellMsg.o Exception.o

CFLAGS += $(SOCKETINC)
LFLAGS += $(SOCKETLIB)
